/// Flutter icons KeodamIcons
/// Copyright (C) 2025 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  KeodamIcons
///      fonts:
///       - asset: fonts/KeodamIcons.ttf
///
/// 
///
library;
import 'package:flutter/widgets.dart';

class KeodamIcons {
  KeodamIcons._();

  static const _kFontFam = 'KeodamIcons';
  static const String? _kFontPkg = null;

  static const IconData logo2 = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
